"""add role to users table

Revision ID: 05552b22ceac
Revises: 87a2bdd30da5
Create Date: 2026-05-04 20:51:06.895196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa





# revision identifiers, used by Alembic.
revision: str = '05552b22ceac'
down_revision: Union[str, Sequence[str], None] = '87a2bdd30da5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.String(length=50), nullable=True, server_default='user'))
    op.execute("UPDATE users SET role = 'user' WHERE role IS NULL")
    op.alter_column('users', 'role', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
