"""password_hash

Revision ID: 20a007882453
Revises: e4e2f41fe76f
Create Date: 2026-04-29 18:13:20.557054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy 




# revision identifiers, used by Alembic.
revision: str = '20a007882453'
down_revision: Union[str, Sequence[str], None] = 'e4e2f41fe76f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(), nullable=True))
    op.execute("UPDATE users SET password_hash = 'temp_hash' WHERE password_hash IS NULL")
    op.alter_column('users', 'password_hash', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
