"""add book with tags

Revision ID: 433278225ad3
Revises: 9e12200f9f78
Create Date: 2026-06-08 20:01:00.523148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy 




# revision identifiers, used by Alembic.
revision: str = '433278225ad3'
down_revision: Union[str, Sequence[str], None] = '9e12200f9f78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
