"""add is_verified to users

Revision ID: 87a2bdd30da5
Revises: 20a007882453
Create Date: 2026-05-01 20:52:40.620518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa





# revision identifiers, used by Alembic.
revision: str = '87a2bdd30da5'
down_revision: Union[str, Sequence[str], None] = '20a007882453'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=True, server_default='False'))
    op.execute("UPDATE users SET is_verified = False WHERE is_verified IS NULL")
    op.alter_column('users', 'is_verified', nullable=False)
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('users', 'is_verified')
    # ### end Alembic commands ###
