"""relate user to book

Revision ID: b343d2795b38
Revises: 05552b22ceac
Create Date: 2026-05-05 15:18:35.709440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa





# revision identifiers, used by Alembic.
revision: str = 'b343d2795b38'
down_revision: Union[str, Sequence[str], None] = '05552b22ceac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('user_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'books', 'users', ['user_id'], ['uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.drop_column('books', 'user_id')
    # ### end Alembic commands ###
