"""update user_id to user_uid

Revision ID: d66e90c1223c
Revises: 54090267d796
Create Date: 2026-06-08 01:19:45.871199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy 




# revision identifiers, used by Alembic.
revision: str = 'd66e90c1223c'
down_revision: Union[str, Sequence[str], None] = '54090267d796'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('user_uid', sa.Uuid(), nullable=True))
    op.drop_constraint(op.f('books_user_id_fkey'), 'books', type_='foreignkey')
    op.create_foreign_key(None, 'books', 'users', ['user_uid'], ['uid'])
    op.drop_column('books', 'user_id')
    op.add_column('reviews', sa.Column('user_uid', sa.Uuid(), nullable=True))
    op.drop_constraint(op.f('reviews_user_id_fkey'), 'reviews', type_='foreignkey')
    op.create_foreign_key(None, 'reviews', 'users', ['user_uid'], ['uid'])
    op.drop_column('reviews', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.create_foreign_key(op.f('reviews_user_id_fkey'), 'reviews', 'users', ['user_id'], ['uid'])
    op.drop_column('reviews', 'user_uid')
    op.add_column('books', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.create_foreign_key(op.f('books_user_id_fkey'), 'books', 'users', ['user_id'], ['uid'])
    op.drop_column('books', 'user_uid')
    # ### end Alembic commands ###
